YUI.add('nfl-lang',function(Y){"use strict";var PI_FIND=/(\d)(\d{3}(?:,\d{3})*(?:\.\d+)?)$/,PI_REPLACE="$1,$2",COLOR_RE=/^#(?:[\dA-F]{3}){1,2}$/,NON_WORD=/[^\w\-]/g;Y.namespace('String');Y.String=Y.merge(Y.String,{capitalize:function(string){return string.charAt(0).toUpperCase()+string.substring(1).toLowerCase();},truncate:function(string,length,truncation){length=length||30;truncation=Y.Lang.isUndefined(truncation)?"\u2026":truncation;return string.length>length?string.slice(0,length-truncation.length)+truncation:string;},truncateAtLastWord:function(string,length,truncation){return string.length>length?Y.String.truncate(string,string.substring(0,length).lastIndexOf(' ')+1,truncation):string;},urlify:function(value){return String(value).replace(NON_WORD,'').toLowerCase();}});Y.Lang=Y.merge(Y.Lang,{isINT:function(value){return Y.Lang.isNumber(value)&&Math.floor(value)===value;},isUINT:function(value){return Y.Lang.isINT(value)&&value>=0;},isColor:function(value){return COLOR_RE.test(value);},toInt:function(value){return parseInt(value,10);},toPrettyInt:function(n,max){var val=parseInt(n,10),workingString,valAsString;if(isNaN(val)){Y.log('Y.Lang.toPrettyInt('+n+', '+max+') -> NaN');return"0";}
if(max&&Math.abs(val)>Math.abs(max)){val=max;}
valAsString=val.toString();while(workingString!==valAsString){workingString=valAsString;valAsString=valAsString.replace(PI_FIND,PI_REPLACE);}
if(val===max){valAsString+='+';}
return valAsString;},toOrd:function(value){var s=String(value),len=s.length,end=s.substr(len-1,1),teen=len>1&&s.substr(len-2,1)==="1",ord="th";if(end==="1"&&!teen){ord="st";}else if(end==="2"&&!teen){ord="nd";}else if(end==="3"&&!teen){ord="rd";}
return ord;},toString:function(value){console.warn("DEPRECATED: Use String(val) instead of Y.Lang.toString(value)");return String(value);},escapeHTML:function(string){return string.replace(/\&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');},K:function(a){return a;},emptyFunction:function(){},addParamsToURL:function(url,params){var hashArray,hash='';if(!url){return'';}
if(url.indexOf('#')>-1){hashArray=url.split('#');url=hashArray[0];hash='#'+hashArray[1];}
return url+
(url.indexOf('?')>-1?'&':'?')+
(Y.Lang.isString(params)?params:Y.QueryString.stringify(params))+
hash;}});},"3.1.1",{requires:['querystring']});;YUI.add('base-generate',function(Y){Y.Base.generate=function(su,st,im){var name='generated-class';if(st&&st.NAME){name=st.NAME;delete st.NAME;}
console.error('Y.Base.generate is deprecated. Use Y.Base.create for '+name+' instead.');return Y.Base.create(name,su,[],im,st);};},"3.3.0",{requires:['base-build']});;YUI.add('datasource-randomize',function(Y){function Randomizable(){this._callback={};}
Randomizable.prototype={}
Randomizable.prototype._osetInterval=Y.DataSource.Local.prototype.setInterval;Randomizable.prototype.setInterval=function(msec,callback){if(typeof callback!=='undefined'){this._callback=callback;}
var fn=Y.bind(function(){var _s=this.get('source');if(_s.indexOf('?')>-1&&_s.indexOf('random=')>-1){var _sp=_s.indexOf('random='),_ep=_s.length;if(_s.substring(_sp).indexOf('&')>-1||_s.substring(_sp).indexOf('&amp;')>-1){_ep=((_s.substring(_sp).indexOf('&amp;')>-1)?(_s.substring(_sp).indexOf('&amp;')+_sp):(_s.substring(_sp).indexOf('&')+_sp))}
_ep=(_s.substring(0,_sp).lastIndexOf('&')==_s.substring(0,_sp).length-1&&_s.substring(_ep).indexOf('&')===0)?_ep+1:_ep;this.set('source',(_s.substring(0,_sp)+_s.substring(_ep)+(((_s.substring(0,_sp)+_s.substring(_ep)).lastIndexOf('&')===(_s.substring(0,_sp)+_s.substring(_ep)).length-1)||(_s.substring(0,_sp)+_s.substring(_ep)).length==0?'':'&')));}
var _cr=(_s.indexOf('?')<0)?'?':'';_cr+=('random='+(new Date().getTime()));this._callback.request=_cr;},this);this.on('response',fn);fn();return this._osetInterval(msec,this._callback);};Y.augment(Y.DataSource.Local,Randomizable,true);},"3.1.1",{requires:['oop','datasource','datasource-local','datasource-polling']});;YUI.add("datasource-get-multi",function(Y){var RESPONSES=[],REQUESTS=[],RESPONSE_COUNT=0,PUB=new Y.EventTarget();PUB.name='multiple datasource response';PUB.publish('response',{broadcast:1,emitFacade:true});function onDataSourceResponse(index,r){var _responses=this.get('responses');if(typeof _responses[index]==='undefined'||_responses[index]===null){RESPONSE_COUNT+=1;}
_responses[index]=r.response.results[0];this.set('responses',_responses);if(RESPONSE_COUNT===this.get('requests').length){this.fire('response',{'response':this.get('responses')});}}
function DSMulti(){DSMulti.superclass.constructor.apply(this,arguments);}
Y.namespace("DataSource").GetMultiple=Y.extend(DSMulti,Y.Base,{initializer:function(config){var _sources=config.sources;this.setSources(_sources);},setSources:function(_sources){try{var _requests=[];Y.Array.each(_sources,function(s){_requests[_requests.length]=(new Y.DataSource.Get({source:s}));_requests[(_requests.length-1)].on('response',Y.bind(onDataSourceResponse,this,(_requests.length-1)));},this);this.set('requests',_requests);}catch(e){console.warn('DataSource.GetMultiple could not process setSources');}},sendRequest:function(){var _requests=this.get('requests');Y.Array.each(_requests,function(r){r.sendRequest();},this);},setInterval:function(intv){var _requests=this.get('requests');Y.Array.each(_requests,function(r){r.setInterval(intv);},this);},_onSetRequest:function(value){REQUESTS=value;return REQUESTS;},_onSetResponse:function(value){RESPONSES=value;return RESPONSES;},destructor:function(){if(this.get('requests').length>0){var _requests=this.get('requests');Y.Array.each(_requests,function(ds){ds.destroy();},this);}}},{NAME:'datasource-multi',NS:'DataSource',ATTRS:{requests:{value:REQUESTS,setter:'this._onSetRequest'},responses:{value:[],setter:'this._onSetResponse'}}});},"3.1.1",{requires:['datasource-polling','datasource-randomize','datasource-get','event-custom']});YUI.add("datasource-io-multi",function(Y){var RESPONSES=[],REQUESTS=[],RESPONSE_COUNT=0,PUB=new Y.EventTarget();PUB.name='multiple datasource response';PUB.publish('response',{broadcast:1,emitFacade:true});function onDataSourceResponse(index,r){var _responses=this.get('responses');if(typeof _responses[index]==='undefined'||_responses[index]===null){RESPONSE_COUNT+=1;}
_responses[index]=eval('('+r.response.results[0].responseText+')');this.set('responses',_responses);if(RESPONSE_COUNT===this.get('requests').length){this.fire('response',{'response':this.get('responses')});}}
function DSIOMulti(){DSIOMulti.superclass.constructor.apply(this,arguments);}
Y.namespace("DataSource").IOMultiple=Y.extend(DSIOMulti,Y.Base,{initializer:function(config){var _sources=config.sources;this.setSources(_sources);},setSources:function(_sources){try{var _requests=[];Y.Array.each(_sources,function(s){_requests[_requests.length]=(new Y.DataSource.IO({source:s}));_requests[(_requests.length-1)].on('response',Y.bind(onDataSourceResponse,this,(_requests.length-1)));},this);this.set('requests',_requests);}catch(e){console.warn('DataSource.IOMultiple could not process setSources');}},sendRequest:function(){var _requests=this.get('requests');Y.Array.each(_requests,function(r){r.sendRequest();},this);},setInterval:function(intv){var _requests=this.get('requests');Y.Array.each(_requests,function(r){r.setInterval(intv);},this);},_onSetRequest:function(value){REQUESTS=value;return REQUESTS;},_onSetResponse:function(value){RESPONSES=value;return RESPONSES;},destructor:function(){if(this.get('requests').length>0){var _requests=this.get('requests');Y.Array.each(_requests,function(ds){ds.destroy();},this);}}},{NAME:'datasource-multi',NS:'DataSource',ATTRS:{requests:{value:REQUESTS,setter:'this._onSetRequest'},responses:{value:[],setter:'this._onSetResponse'}}});},"3.1.1",{requires:['datasource-polling','datasource-randomize','datasource-io','event-custom']});YUI.add('datasource-randomize',function(Y){function Randomizable(){this._callback={};}
Randomizable.prototype={}
Randomizable.prototype._osetInterval=Y.DataSource.Local.prototype.setInterval;Randomizable.prototype.setInterval=function(msec,callback){if(typeof callback!=='undefined'){this._callback=callback;}
this.on('response',Y.bind(function(){var _s=this.get('source');if(_s.indexOf('?')>-1&&_s.indexOf('random=')>-1){var _sp=_s.indexOf('random='),_ep=_s.length;if(_s.substring(_sp).indexOf('&')>-1||_s.substring(_sp).indexOf('&amp;')>-1){_ep=((_s.substring(_sp).indexOf('&amp;')>-1)?(_s.substring(_sp).indexOf('&amp;')+_sp):(_s.substring(_sp).indexOf('&')+_sp))}
_ep=(_s.substring(0,_sp).lastIndexOf('&')==_s.substring(0,_sp).length-1&&_s.substring(_ep).indexOf('&')===0)?_ep+1:_ep;this.set('source',(_s.substring(0,_sp)+_s.substring(_ep)+(((_s.substring(0,_sp)+_s.substring(_ep)).lastIndexOf('&')===(_s.substring(0,_sp)+_s.substring(_ep)).length-1)||(_s.substring(0,_sp)+_s.substring(_ep)).length==0?'':'&')));}
var _cr=(_s.indexOf('?')<0)?'?':'';_cr+=('random='+(new Date().getTime()));this._callback.request=_cr;},this));this._osetInterval(msec,this._callback);};Y.augment(Y.DataSource.Local,Randomizable,true);},"3.1.1",{requires:['oop','datasource','datasource-local','datasource-polling']});YUI.add('datasource-incrementable',function(Y){function Incrementable(){this._callback={};}
Incrementable.prototype={}
Incrementable.prototype._osetInterval=Y.DataSource.Local.prototype.setInterval;Incrementable.prototype._incPrefix='_';Incrementable.prototype._incPostfix='';Incrementable.prototype._incNumber=0;Incrementable.prototype._lastIncNumber=-1;Incrementable.prototype._intId=null;Incrementable.prototype.setIncrement=function(_inc){this._incNumber=_inc;};Incrementable.prototype.setLastIncrement=function(_inc){this._lastIncNumber=_inc;};Incrementable.prototype.setInterval=function(msec,callback){if(typeof callback!=='undefined'){this._callback=callback;}
if(this._intId!==null&&typeof this._intId!=='undefined'){clearInterval(this._intId);}
this.on('response',Y.bind(function(){var _s=this.get('source');if(_s.indexOf('?')>-1&&_s.indexOf('random=')>-1){var _sp=_s.indexOf('random='),_ep=_s.length;if(_s.substring(_sp).indexOf('&')>-1||_s.substring(_sp).indexOf('&amp;')>-1){_ep=((_s.substring(_sp).indexOf('&amp;')>-1)?(_s.substring(_sp).indexOf('&amp;')+_sp):(_s.substring(_sp).indexOf('&')+_sp))}
_ep=(_s.substring(0,_sp).lastIndexOf('&')==_s.substring(0,_sp).length-1&&_s.substring(_ep).indexOf('&')===0)?_ep+1:_ep;this.set('source',(_s.substring(0,_sp)+_s.substring(_ep)+(((_s.substring(0,_sp)+_s.substring(_ep)).lastIndexOf('&')===(_s.substring(0,_sp)+_s.substring(_ep)).length-1)||(_s.substring(0,_sp)+_s.substring(_ep)).length==0?'':'&')));}
this._incNumber=this._incNumber+1;if(this._lastIncNumber>=0&&this._incNumber>=this._lastIncNumber){clearInterval(this._intId);}
var _cr=this._incPrefix+(this._incNumber)+this._incPostfix;_cr+=(_s.indexOf('?')<0)?'?':'';_cr+=('random='+(new Date().getTime()));this._callback.request=_cr;},this));this._intId=this._osetInterval(msec,this._callback);};Y.augment(Y.DataSource.Local,Incrementable,true);},"3.1.1",{requires:['oop','datasource','datasource-local','datasource-polling']});;YUI.add("nfl-user-fantasy",function(Y){var PLUSES=/\+/g,SPACE=' ',FANTASY_COOKIE_NAME='ff',FANTASY_CORE_GAME_REGEX=/10\d{4}/,FANTASY_GAMES_SEPARATOR="^",FANTASY_GAME_DATA_SEPARATOR="|",FANTASY_GAMES_ENTRY_SEPARATOR="#",FANTASY_GAMES_ENTRY_TYPE_SEPARATOR="@",FANTASY_GAMES_ENTRY_TYPE_LEAGUE="L",FANTASY_GAMES_ENTRY_TYPE_AUTOPICK="A",FANTASY_GAMES_ENTRY_TYPE_ENTRY="E",FANTASY_GAMES_ENTRY_TYPE_GENIUS="G",FANTASY_GAMES_ENTRY_DATA_SEPARATOR="~";var Constants=nfl.constants;var APP_KEY=((typeof nfl.constants.FANTASY_APP_KEY==='undefined')?'oe5avcjshxq6407t':nfl.constants.FANTASY_APP_KEY),WEEK=1,TOKEN='',DATA_SOURCES={'authtoken':(new Y.DataSource.Get({source:Constants.FANTASY_API+'/internal/user/authtoken?format=json&appKey=ymd97gxs2bxtzbj7&'})),'leagues':(new Y.DataSource.Get({source:Constants.FANTASY_API+'/user/leagues?format=json&authToken='+TOKEN+'&'})),'leaguesinternal':(new Y.DataSource.Get({source:Constants.FANTASY_API+'/internal/user/leagues?format=json&'})),'matchups':(new Y.DataSource.GetMultiple({})),'rosters':(new Y.DataSource.GetMultiple({})),'rostersinternal':(new Y.DataSource.Get({source:Constants.FANTASY_API+'/internal/user/teams/roster?format=json&'})),'playoffchallenge':(new Y.DataSource.Get({source:Constants.PREDICTPICK_API+'/user/games?format=json&nflUsername='})),'fancookie':(new Y.DataSource.Local({})),'leagueplayers':{}};var REQUESTED={'authtoken':false,'leagues':false,'matchups':false,'players':false,'rosters':false,'playoffchallenge':false};var getAuthToken=function(){DATA_SOURCES.authtoken.sendRequest();}
var _onDataSourceRequest=function(a,r){REQUESTED[a]=true;}
var _onDataSourceError=function(a,r){var _evt=new Y.EventTarget();_evt.name='fantasy user data error';_evt.publish(a+':error',{broadcast:1,emitFacade:true});this.fire(a+':error',r);this.fire('error',r);}
var _onDataSourceResponse=function(a,r){if(typeof r!=='undefined'){if(typeof r.error!=='undefined'||typeof r.errors!=='undefined'){return}}
this.set(a,r);var _evt=new Y.EventTarget();_evt.name='fantasy user data response';_evt.publish(a+':response',{broadcast:1,emitFacade:true});this.fire(a+':response',r);}
var _onWriteDataSourceResponse=function(a,r){if(typeof r!=='undefined'){if(typeof r.data.errors!=='undefined'){var _evt=new Y.EventTarget();_evt.name='fantasy user write error';_evt.publish(a+':error',{broadcast:1,emitFacade:true});this.fire(a+':error',r);return}
var _evt=new Y.EventTarget();_evt.name='fantasy user write response';_evt.publish(a+':response',{broadcast:1,emitFacade:true});this.fire(a+':response',r);}}
function FantasyUserPlugin(){FantasyUserPlugin.superclass.constructor.apply(this,arguments);}
Y.namespace('NFL.Fantasy').ServiceUtility=Y.extend(FantasyUserPlugin,Y.Plugin.Base,{initializer:function(config){this.USER=this.get('host');DATA_SOURCES.playoffchallenge=(new Y.DataSource.Get({source:Constants.PLAYOFF_CHALLENGE_API+'/user/games?format=json&nflUsername='+this.USER.get('username')+'&'}))
if(config.week){WEEK=config.week;}
this.on('weekChange',function(e){WEEK=e.newVal;});var fcookie=Y.Cookie.get(FANTASY_COOKIE_NAME,Y.QueryString.parse);if(fcookie&&fcookie!=='0'){DATA_SOURCES.fancookie.set('source',function(fcookie){var data=arguments[0]||Y.Cookie.get(FANTASY_COOKIE_NAME,Y.QueryString.parse),parsedFantasyData;parsedFantasyData=Y.NFL.Fantasy.ServiceUtility.PARSE_FANTASY_COOKIE_DATA(data);return parsedFantasyData;}());}
DATA_SOURCES.authtoken.on('response',Y.bind(_onDataSourceResponse,this,'authtoken'));DATA_SOURCES.leagues.on('response',Y.bind(_onDataSourceResponse,this,'leagues'));DATA_SOURCES.leaguesinternal.on('response',Y.bind(_onDataSourceResponse,this,'leaguesinternal'));DATA_SOURCES.rostersinternal.on('response',Y.bind(_onDataSourceResponse,this,'rostersinternal'));DATA_SOURCES.matchups.on('response',Y.bind(_onDataSourceResponse,this,'matchups'));DATA_SOURCES.rosters.on('response',Y.bind(_onDataSourceResponse,this,'rosters'));DATA_SOURCES.fancookie.on('response',Y.bind(_onDataSourceResponse,this,'fancookie'));DATA_SOURCES.playoffchallenge.on('response',Y.bind(_onDataSourceResponse,this,'playoffchallenge'));DATA_SOURCES.authtoken.on('request',Y.bind(_onDataSourceRequest,this,'authtoken'));DATA_SOURCES.leagues.on('request',Y.bind(_onDataSourceRequest,this,'leagues'));DATA_SOURCES.leaguesinternal.on('request',Y.bind(_onDataSourceRequest,this,'leaguesinternal'));DATA_SOURCES.matchups.on('request',Y.bind(_onDataSourceRequest,this,'matchups'));DATA_SOURCES.rostersinternal.on('request',Y.bind(_onDataSourceRequest,this,'rostersinternal'));DATA_SOURCES.rosters.on('request',Y.bind(_onDataSourceRequest,this,'rosters'));DATA_SOURCES.fancookie.on('request',Y.bind(_onDataSourceRequest,this,'fancookie'));DATA_SOURCES.playoffchallenge.on('request',Y.bind(_onDataSourceRequest,this,'playoffchallenge'));DATA_SOURCES.authtoken.on('error',Y.bind(_onDataSourceError,this,'authtoken'));DATA_SOURCES.leagues.on('error',Y.bind(_onDataSourceError,this,'leagues'));DATA_SOURCES.leaguesinternal.on('error',Y.bind(_onDataSourceError,this,'leaguesinternal'));DATA_SOURCES.matchups.on('error',Y.bind(_onDataSourceError,this,'matchups'));DATA_SOURCES.rostersinternal.on('error',Y.bind(_onDataSourceError,this,'rostersinternal'));DATA_SOURCES.rosters.on('error',Y.bind(_onDataSourceError,this,'rosters'));DATA_SOURCES.fancookie.on('error',Y.bind(_onDataSourceError,this,'fancookie'));DATA_SOURCES.playoffchallenge.on('error',Y.bind(_onDataSourceError,this,'playoffchallenge'));},_onTokenSet:function(value){if(value!==null){if(value.response.results.length>0){if(typeof value.response.results[0].errors!=='undefined'){if(value.response.results[0].errors.length>0){DATA_SOURCES.authtoken.fire('error');return;}}
value=value.response.results[0].response.authToken;TOKEN=value;DATA_SOURCES.leagues=(new Y.DataSource.Get({source:Constants.FANTASY_API+'/user/leagues?format=json&authToken='+value+'&'}));DATA_SOURCES.leagues.on('response',Y.bind(_onDataSourceResponse,this,'leagues'));DATA_SOURCES.leagues.on('request',Y.bind(_onDataSourceRequest,this,'leagues'));}}
return value},_onLeaguesSet:function(value){if(value!==null){if(value.response.results.length>0){value=value.response.results[0].leagues;var matchups=[];var rosters=[];Y.Array.each(value,function(_l){matchups[matchups.length]=(Constants.FANTASY_API+'/league/team/matchup?leagueId='+_l.leagueId+'&teamId='+_l.teamId+'&week='+WEEK+'&format=json&authToken='+TOKEN+'&');rosters[rosters.length]=(Constants.FANTASY_API+'/league/team/roster?leagueId='+_l.leagueId+'&teamId='+_l.teamId+'&week='+WEEK+'&format=json&authToken='+TOKEN+'&');},this);console.log('set matchups/rosters from league sets',matchups);if(matchups.length>0){DATA_SOURCES.matchups.setSources(matchups);}
if(rosters.length>0){DATA_SOURCES.rosters.setSources(rosters);}}}
return value},_onLeagueInternalSet:function(value){if(value!==null){if(value.response.results.length>0){value=value.response.results[0].leagues;var matchups=[];var rosters=[];Y.Array.each(value,function(_l){matchups[matchups.length]=(Constants.FANTASY_API+'/league/team/matchup?leagueId='+_l.id+'&teamId='+_l.team.id+'&week='+WEEK+'&format=json&authToken='+TOKEN+'&');rosters[rosters.length]=(Constants.FANTASY_API+'/league/team/roster?leagueId='+_l.id+'&teamId='+_l.team.id+'&week='+WEEK+'&format=json&authToken='+TOKEN+'&');},this);console.log('set matchups/rosters from league sets',matchups);if(matchups.length>0){DATA_SOURCES.matchups.setSources(matchups);}
if(rosters.length>0){DATA_SOURCES.rosters.setSources(rosters);}}}
return value},sendAndBind:function(attrKey,callback){if(typeof this.get(attrKey)!=='undefined'&&this.get(attrKey)!==null&&typeof callback!=='undefined'){try{callback(this.get(attrKey));}catch(e){}
return}
if(attrKey=='leaguesinternal'&&this.get('authtoken')==null){if(!REQUESTED['leaguesinternal']){DATA_SOURCES['leaguesinternal'].sendRequest();}
return}
if(attrKey=='leagues'&&this.get('authtoken')==null){console.warn('league retrieval without authtoken. getting authtoken first',this.get('authtoken'));this.on('authtoken:response',Y.bind(function(){console.log('authtoken response, proceeding with leagues..');this.getService('leagues')},this));if(!REQUESTED['authtoken']){DATA_SOURCES['authtoken'].sendRequest();}
return}
if(attrKey=='matchups'&&(this.get('leagues')==null&&this.get('leaguesinternal')==null)){this.on('leagues:response',Y.bind(function(){console.log('leagues response, proceeding with matchups..');this.getService('matchups')},this));if(!REQUESTED['leagues']){DATA_SOURCES['leagues'].sendRequest();}
return}
if(attrKey=='rosters'&&this.get('leagues')==null){this.on('leagues:response',Y.bind(function(){console.log('leagues response, proceeding with rosters..');this.getService('rosters')},this));this.getService('leagues');return}
if(attrKey=='playoffchallenge'){if(!REQUESTED['playoffchallenge']){DATA_SOURCES['playoffchallenge'].sendRequest();}
return}
DATA_SOURCES[attrKey].sendRequest();},getService:function(serviceKey,callback){if(typeof callback!=='undefined'){this.on(serviceKey+':response',callback);}
if(this.get(serviceKey)!==null&&typeof callback!=='undefined'){callback(this.get(serviceKey));return this.get(serviceKey);}
this.sendAndBind(serviceKey,callback);},setServiceInterval:function(serviceKey,intv){if(typeof DATA_SOURCES[serviceKey]==='undefined'||DATA_SOURCES[serviceKey]===null){return}
DATA_SOURCES[serviceKey].setInterval(intv);},dropPlayer:function(playerId,leagueId,teamId){var _rd=new Y.DataSource.Get({source:Constants.FANTASY_API+'/league/team/dropplayer?format=json&leagueId='+leagueId+'&teamId='+teamId+'&dropPlayerId='+playerId+'&authToken='+this.get('authtoken')+'&'});_rd.on('response',Y.bind(_onWriteDataSourceResponse,this,'rosteredit'));_rd.sendRequest();},addPlayer:function(playerId,leagueId,teamId){var _rd=new Y.DataSource.Get({source:Constants.FANTASY_API+'/league/team/addplayer?format=json&leagueId='+leagueId+'&teamId='+teamId+'&addPlayerId='+playerId+'&authToken='+this.get('authtoken')+'&'});_rd.on('response',Y.bind(_onWriteDataSourceResponse,this,'rosteredit'));_rd.sendRequest();},getPlayersForLeague:function(leagueId){DATA_SOURCES['leagueplayers'][leagueId]=(new Y.DataSource.Get({source:Constants.FANTASY_API+'/league/players?format=json&leagueId='+leagueId+'&playerStatus=taken&count=100&authToken='+this.get('authtoken')+'&'}));DATA_SOURCES['leagueplayers'][leagueId].on('response',Y.bind(_onDataSourceResponse,this,'leagueplayers'));DATA_SOURCES['leagueplayers'][leagueId].sendRequest();},destructor:function(){DATA_SOURCES.authtoken.destroy();DATA_SOURCES.leagues.destroy();DATA_SOURCES.leaguesinternal.destroy();DATA_SOURCES.matchups.destroy();DATA_SOURCES.rosters.destroy();DATA_SOURCES.playoffchallenge.destroy();}},{NAME:'nfl-fantasy-plugin',NS:'fantasy',ATTRS:{'authtoken':{value:null,setter:'_onTokenSet'},'leagues':{value:null,setter:'_onLeaguesSet'},'leaguesinternal':{value:null,setter:'_onLeagueInternalSet'},'playoffchallenge':{value:null},'matchups':{value:null},'rosters':{value:null},'rostersinternal':{value:null},'fancookie':{value:null},'leagueplayers':{value:{}},'week':{value:WEEK}},PARSE_FANTASY_COOKIE_DATA:function(parsedFantasyCookie){if(this._parsedFantasyData){}
var parsedData={leagues:[],autopicks:[],casualGamesEntries:[],genius:{},user:{id:parsedFantasyCookie.fu||''}},games=[];games=(parsedFantasyCookie.g||'').split(FANTASY_GAMES_SEPARATOR);Y.Array.each(games,function(game){if(game){var tmp=game.split(FANTASY_GAME_DATA_SEPARATOR),gameId=tmp[0],gameData=tmp[1],gameEntries=gameData.split(FANTASY_GAMES_ENTRY_SEPARATOR);Y.Array.each(gameEntries,function(entry){var tmp=entry.split(FANTASY_GAMES_ENTRY_TYPE_SEPARATOR),entryType=tmp[0],entryData=tmp.length>1?tmp[1].split(FANTASY_GAMES_ENTRY_DATA_SEPARATOR):null;;if(!entryData){return;}
switch(entryType){case FANTASY_GAMES_ENTRY_TYPE_LEAGUE:parsedData.leagues.push({id:entryData[0],name:entryData[1],team:{id:entryData[2],name:entryData[3]},gameId:gameId,draftDate:'',draftTime:'',draftType:''});break;case FANTASY_GAMES_ENTRY_TYPE_AUTOPICK:parsedData.autopicks.push({id:entryData[0],name:entryData[1],gameId:gameId});break;case FANTASY_GAMES_ENTRY_TYPE_ENTRY:parsedData.casualGamesEntries.push({id:entryData[0],name:entryData[1],gameId:gameId});break;case FANTASY_GAMES_ENTRY_TYPE_GENIUS:parsedData.genius={score:entryData[0],rank:entryData[1]}
break;}});}});this._parsedFantasyData=parsedData;return this._parsedFantasyData;}});},"3.1.1",{requires:['plugin','cookie','querystring-parse','datasource-get','datasource-polling','datasource-randomize','datasource-get-multi']});;YUI.add('user-meta',function(Y){Y.UserMetaData=Y.Base.create("user-meta",Y.Plugin.Base,[],{_SUBS:null,_FANTASY:null,_SUBSLOADED:false,_FANTASYLOADED:false,_PLAYOFFCHALLENGELOADED:false,_LOADING:[],_EH:[],initializer:function(config){this._EH.push(this.on('chainCompleteChange',Y.bind(function(){this.get('host').fire('metadataLoaded',this.getAttrs());},this)));if(typeof window.NFL_GLOBAL_CACHE==='undefined'){window.NFL_GLOBAL_CACHE={};}
try{if(typeof window.NFL_GLOBAL_CACHE.NFL_SUBS!=='undefined'&&window.NFL_GLOBAL_CACHE.NFL_SUBS!==null){console.warn('getting subs from data cache: ',window.NFL_GLOBAL_CACHE.NFL_SUBS);this._onSubsResponse({subscriptions:window.NFL_GLOBAL_CACHE.NFL_SUBS});}else{if(Y.Array.indexOf(this._LOADING,'SUBS')<=0){this._LOADING.push('SUBS');this._SUBS=new Y.NFL.Subscriptions({user:this.get('host'),onResponse:Y.bind(this._onSubsResponse,this)});}}}catch(e){console.warn('this is so weird.. ',e);}
this._FANTASY=this.get('host').plug(Y.NFL.Fantasy.ServiceUtility);this._EH.push(this.get('host').fantasy.on('playoffchallenge:error',Y.bind(this._onPCResponse,this),this));this.get('host').fantasy.getService('fancookie',Y.bind(this._onFantasyCookieResponse,this));},getPC:function(){if(typeof window.NFL_GLOBAL_CACHE.NFL_PC!=='undefined'&&window.NFL_GLOBAL_CACHE.NFL_PC!==null){var _data=window.NFL_GLOBAL_CACHE.NFL_PC;if(_data!==null){var _package={response:{results:[_data]}};console.info('  getting pc data from local cache storage: ',_package);this._onPCResponse(_package);return}}
if(window.NFL_GLOBAL_CACHE.NFL_PCLOADING!==true){window.NFL_GLOBAL_CACHE.NFL_PCLOADING=true;this.get('host').fantasy.getService('playoffchallenge',Y.bind(this._onPCResponse,this));}},_onPCResponse:function(event){this._PLAYOFFCHALLENGELOADED=true;if(event.type!=='dataSourceGet:error'){var _data=event.response.results[0];if(typeof window.NFL_GLOBAL_CACHE.NFL_PC==='undefined'||window.NFL_GLOBAL_CACHE.NFL_PC===null){window.NFL_GLOBAL_CACHE.NFL_PC=_data;}
if(_data.user){this.set('isPlayoffChallengeUser',true);this.set('playoffChallengeUserID',_data.user.id);if(_data.user.games.length>0){var _entries=[];for(var _i=0;_i<_data.user.games.length;_i++){var _game=_data.user.games[_i];if(typeof _game.entry!=='undefined'&&_game.entry!==null){_entries.push(_game);}}
if(_entries.length>0){this.set('playoffChallengeEntries',_entries);}}}}
this.get('host').fire('playoffChallengeLoaded',this.getAttrs());},_onSubsResponse:function(e){this._SUBSLOADED=true;var _subs=e.subscriptions;window.NFL_GLOBAL_CACHE.NFL_SUBS=_subs;this.set('subscriptions',_subs);if(Y.Array.indexOf(_subs,'GAME_PASS')>-1){this.set('hasGP',true);}
if(Y.Array.indexOf(_subs,'FIELD_PASS')>-1){this.set('hasFP',true);}
if(Y.Array.indexOf(_subs,'GAME_REWIND')>-1){this.set('hasGR',true);}
if(Y.Array.indexOf(_subs,'PRESEASON_LIVE')>-1){this.set('hasPL',true);}
if(Y.Array.indexOf(_subs,'NETWORK_ONLINE')>-1){this.set('hasNetwork',true);}
this._checkChainLoadSequence();},_onFantasyCookieResponse:function(e){if(e.response){if(e.response.results){if(e.response.results.length>0){var _c=e.response.results[0];if(_c&&_c!==null){this._FANTASYLOADED=true;this.set('fantasyLeagues',_c.leagues);this.set('fantasyAutoPicks',_c.autopicks);if(_c.user){if(_c.user.id!==""){this.set('isFantasyUser',true);this.set('fantasyUserID',_c.user.id);}}
this.set('fantasyLoadComplete',true);this._checkChainLoadSequence();return;}}}}
this.get('host').fantasy.getService('leaguesinternal',Y.bind(this._onFantasyLeaguesResponse,this));},_onFantasyLeaguesResponse:function(r){this._FANTASYLOADED=true;try{var _data=r;if(typeof _data.data!=='undefined'||_data.data!==null){_data=_data.data;}
if(typeof _data!=='undefined'&&_data!==null){if((typeof _data.leagues!=='undefined'&&_data.leagues!==null)||(typeof _data.autopicks!=='undefined'&&_data.autopicks!==null)){if(_data.leagues.length>0||_data.autopicks.length>0){this.set('fantasyLeagues',_data.leagues);this.set('fantasyAutoPicks',_data.autopicks);if(_data.user){if(_data.user.id!==""&&_data.user.id!==null&&typeof _data.user.id!=='undefined'){this.set('isFantasyUser',true);this.set('fantasyUserID',_data.user.id);}}}}}}catch(e){console.error('_onFantasyLeaguesResponse Error: ',e,r);}
this.set('fantasyLoadComplete',true);this._checkChainLoadSequence();},hasSubs:function(){return(this.get('subscriptions').length>0)},_checkChainLoadSequence:function(){if(this._SUBSLOADED&&this._FANTASYLOADED){this.set('chainComplete',true);}
return this.get('chainComplete');},hasFantasyTeams:function(){if(typeof this.get('fantasyLeagues')!=='undefined'){if(this.get('fantasyLeagues').length>0){return true}}
if(typeof this.get('fantasyAutoPicks')!=='undefined'){if(this.get('fantasyAutoPicks').length>0){return true}}
return false},hasPlayoffChallengeEntries:function(){if(this.get('playoffChallengeEntries')){if(typeof this.get('playoffChallengeEntries')!=='undefined'&&this.get('playoffChallengeEntries')!==null){return(this.get('playoffChallengeEntries').length>0)}}
return false},hasPlayoffChallengePicks:function(_req){var _entries=this.get('playoffChallengeEntries');if(_entries.length<=0){return false;}
var _ret=false;Y.Array.each(_entries,function(_game){if(typeof _game.entry.picks!=='undefined'&&_game.entry.picks!==null){if(typeof _game.entry.picks.rosterSlots!=='undefined'&&_game.entry.picks.rosterSlots!==null){if(_game.entry.picks.rosterSlots.length>0){var _required=(typeof _req!=='undefined'&&_req>0)?_req:8,_has=0;for(var _i=0;_i<_game.entry.picks.rosterSlots.length;_i++){if(_game.entry.picks.rosterSlots[_i].playerId!==null&&_game.entry.picks.rosterSlots[_i].playerId!==''){_has++;}}
_ret=(_has>=_required);}}}},this);return _ret},destroy:function(){this.get('host').unplug(Y.NFL.Fantasy.ServiceUtility);Y.Array.each(this.EVTHANDLES,function(handle){if(handle)handle.detach();});}},{'NS':'metadata','NAME':'user-metadata','ATTRS':{isLoggedIn:{value:true},chainComplete:{value:false},fantasyLoadComplete:{value:false},isFantasyUser:{value:false},playoffChallengeUserID:{value:null},isPlayoffChallengeUser:{value:false},playoffChallengeEntries:{value:[]},hasPlayoffChallengeEntries:{value:false,getter:'hasPlayoffChallengeEntries'},hasPlayoffChallengePicks:{value:false,getter:'hasPlayoffChallengePicks'},fantasyUserID:{value:null},fantasyLeagues:{value:[]},fantasyAutoPicks:{value:[]},hasFantasyTeams:{value:false,getter:'hasFantasyTeams'},hasGP:{value:false},hasAP:{value:false},hasFP:{value:false},hasGR:{value:false},hasNetwork:{value:false},hasPL:{value:false},hasSubscriptions:{value:false,getter:'hasSubs'},subscriptions:{value:[]}}});},"3.1.1",{requires:['plugin','base','event-custom','cookie','nfl-subscriptions','nfl-user-fantasy','datasource-io']});