YUI.add('ads-v3',function(Y){"use strict";var instances=nfl.ads.instances=nfl.ads.instances||{},toInt=function(val){var int=parseInt(val,10);return isNaN(int)?val:int;},Ads=Y.namespace('NFL.Ads'),COOKIE_AAMNFL='aamnfl',COOKIE_AAMDID='aam_did',Constants=nfl.constants,isMobile=Constants.IS_MOBILE,isTablet=Constants.IS_TABLET,AdConf=Constants.AD_CONF,ATTRS={id:{value:null,writeOnce:true,getter:function(val){return val||Y.guid();}},divId:{getter:'_getDivId'},path:{value:null,getter:'_getPath',setter:'_setPath'},tile:{getter:function(){return Y.Object.keys(instances).length;}},dcopt:{value:''},width:{value:0,setter:toInt},height:{value:0,setter:toInt},aamnfl:{value:'',getter:function(){return Y.Cookie.exists(COOKIE_AAMNFL)?(this.get('isLegacy')?Y.Cookie.get(COOKIE_AAMNFL):encodeURIComponent(Y.Cookie.get(COOKIE_AAMNFL).replace(/;/g,'&'))):'';}},aam_did:{value:'',getter:function(){return Y.Cookie.exists(COOKIE_AAMDID)?Y.Cookie.get(COOKIE_AAMDID):'';}},sizes:{value:[],setter:function(value){Y.Array.each(Y.Lang.isArray(value)?value:[value],function(item,i){Y.Array.each(item,function(dim,k){item[k]=toInt(dim);});value[i]=item;});return value;}},html:{value:""},size:{readOnly:true,getter:function(){return[this.get("width"),this.get("height")].join("x");}},adUnit:{getter:'_getAdUnit'},slotName:{getter:'_getSlotName'},targeting:{getter:'_getTargeting'},adSlot:{getter:'_getAdSlot',readOnly:true},correlator:{getter:'_getCorrelator',readOnly:true},isLegacy:{value:false,writeOnce:true},isSticky:{value:false,setter:function(val){return(val==="true");}},renderOnEvent:{value:false,setter:function(val){return val;}},shouldRenderWhenViewable:{value:false,setter:function(val){return(val==="true");}},viewabilityDuration:{value:false,setter:function(val){return 3500}}},outOfPageSlot,interstitialId='ad'+Y.Lang.now()+'interstitial',qs=Y.QueryString.parse(Y.config.win.location.search.substring(1)),testParam=qs&&qs.test,isDebug=qs&&qs.ad_debug;Ads.Ad=Y.Base.create("ad",Y.Widget,[],{addAdAttrs:function(value,key){if(!ATTRS.hasOwnProperty(key)&&key!=='render'){if(isDebug){console.log('ad attr added',key);}
this.addAttr(key,{value:value});}},initializer:function(config){var id=this.get("id");Y.Object.each(config||{},this.addAdAttrs,this);this.publish(Ads.Ad.AD_RENDERED,{broadcast:2});if(instances[id]){console.warn('Ad: '+id+' has been already registered, make sure id is unique');this.set('id',id+'-1');}
instances[id]=this;if(config.path){this.set('path',config.path);}
if(!config.sizes&&config.size){this.set('sizes',[config.size]);}
if(!config.sizes&&config.width&&config.height){this.set('sizes',[[toInt(config.width),toInt(config.height)]]);}
if(config.interstitial){config.height='1px';}},_getAdUnit:function(value){if(!value){value=['nfl',AdConf.env,AdConf.site,'/',AdConf.zone].join('');}
return value;},_getSlotName:function(value){if(!value){value=['',AdConf.networkId,this.get('adUnit')].join('/');}
return value;},_getTargeting:function(value){value=value||{};if(!value.url&&!value.s1){value=Y.merge(value,Y.QueryString.parse([AdConf.pageKeyValues,AdConf.zoneKeys,AdConf.zoneUrl].join(';'),';'));}
return value;},_getDivId:function(value){if(!value){value=this.get('contentBox').get('id');}
return value;},_getCorrelator:function(){return Constants.AD_RANDOM;},_getAdSlot:function(){return this._adSlot;},_getPath:function(){var slotName=this.get('slotName'),targeting=this.get('targeting'),sizes=this.get('sizes'),size=(sizes&&sizes[0])?sizes[0]:[this.get('width'),this.get('height')],qs={sz:size.join('x'),iu:slotName,tile:this.get('tile'),t:encodeURIComponent(Y.QueryString.stringify(targeting)),c:this.get('correlator')},escapeStore=Y.QueryString.escape,qsStr;Y.QueryString.escape=function(value){return value;};qsStr='http://pubads.g.doubleclick.net/gampad/ads?'+Y.QueryString.stringify(qs);Y.QueryString.escape=escapeStore;return qsStr;},_setPath:function(value){var path=Y.Lang.sub(value,this.getAttrs()),targeting;if(value.search('ad.doubleclick.net')>-1){this.set('isLegacy',true);var adUnit,regex=/http:\/\/ad.doubleclick.net\/([^\/]+)\/([^;]+)(.+)/,result=regex.exec(path);adUnit=result&&result[2];targeting=Y.QueryString.parse(result&&result[3],';');this._excludeProps(targeting);if(adUnit){this.set('adUnit',adUnit);}}else{var slotName,qs=Y.QueryString.parse(path.substr(path.indexOf('?')+1));slotName=qs.iu;targeting=Y.QueryString.parse(qs.t);this._excludeProps(qs);if(slotName){this.set('slotName',slotName);}}
if(targeting){this.set('targeting',targeting);}
return value;},checkElementVisible:function(){if(!this.isVisible){this.isVisible=this.isElementVisible();if(!this.checkElementEvent){this.checkElementEvent=Y.on("scroll",Y.throttle(Y.bind(function(){this.checkElementVisible();},this),20));}
if(this.isVisible){if(this.checkElementEvent){this.checkElementEvent.detach();this.checkElementEvent=null;}
this.syncUI();this.isVisible=false;}}
return this.isVisible},isElementVisible:function(){var adNode=this.get("boundingBox"),adRegion=adNode.get('region'),width=this.get("width"),height=this.get("height");if(!adRegion){return false;}
var offsetWidth=width*.10,offsetHeight=height*.10,innerWidth=window.innerWidth,innerHeight=window.innerHeight,boundsTop=adNode.getY(),boundsLeft=adNode.getX(),boundsRight=boundsLeft+offsetWidth,boundsBottom=boundsTop+offsetHeight;var viewport={top:window.scrollY||document.documentElement.scrollTop,left:window.scrollX||document.documentElement.scrollLeft};viewport.right=viewport.left+window.innerWidth;viewport.bottom=viewport.top+window.innerHeight;var isVisible=(!(viewport.right<boundsLeft||viewport.left>boundsRight||viewport.bottom<boundsTop||viewport.top>boundsBottom));if(isDebug){console.log(this.get("slotName"),"isVisible: "+isVisible);}
return isVisible;},renderUI:function(){},bindUI:function(){this.after('targetingChange',this._setSlotTargeting,this);},syncUI:function(targeting){if(this.get("renderOnEvent")&&!this.isEventTriggered){Y.once(this.get("renderOnEvent"),(function(){this.isEventTriggered=true;this.syncUI(targeting);}).bind(this));return;}
if(isDebug){console.group(this.get("slotName"));}
var isVisible=this.get("shouldRenderWhenViewable")?this.checkElementVisible():true;if(isVisible){var html=this.get("html");if(html&&!targeting){this._uiRenderCompanion(this.get("contentBox"),html);}else{if(this.isRendered){if(targeting){this.set('targeting',targeting);}
this._queue(this._refresh);}else{this._queue(this._render);this.isRendered=true}}}
if(isDebug&&!isVisible){console.log("not-visible");}
if(this.get('isSticky')&&!this.stickyScrollEvent){this.stickyAdProps={};this.stickyScrollEvent=Y.on('scroll',Y.throttle(Y.bind(this.onScrollSticky,this),10));this.onScrollSticky();}
if(isDebug){console.groupEnd(this.get("slotName"));}},addSticky:function(){var adNode=this.get('boundingBox'),props=this.stickyAdProps;props.isFixedPosition=true;props.top=adNode.getComputedStyle('top');props.width=adNode.get('region').width;adNode.addClass('yui3-ad-fixed');adNode.removeClass('yui3-ad-transition');adNode.setStyles({'top':0,'margin-left':-(props.width/2)+"px"});adNode.ancestor().setStyles({'height':this.get('height')});this.stickyViewabilityTimeout=window.setTimeout(this.onStickyAdViewabilityReached.bind(this),this.get('viewabilityDuration'));},removeSticky:function(){var adNode=this.get('boundingBox'),props=this.stickyAdProps;if(this.stickyViewabilityTimeout){window.clearTimeout(this.stickyViewabilityTimeout);this.stickyViewabilityTimeout=null;}
props.isFixedPosition=false;props.y=0;adNode.removeClass('yui3-ad-fixed');adNode.removeClass('yui3-ad-transition');adNode.setStyles({'top':props.top,'margin-left':'auto','width':props.width});adNode.ancestor().setStyles({'height':'auto'});},onStickyAdViewabilityReached:function(){var adNode=this.get('boundingBox'),props=this.stickyAdProps,scrollY=window.scrollY||document.documentElement.scrollTop;adNode.addClass('yui3-ad-transition');adNode.setStyles({'top':(props.y-scrollY)+"px"});this.stickyViewabilityTimeout=window.setTimeout(this.removeSticky.bind(this),600);if(this.stickyScrollEvent){this.stickyScrollEvent.detach();this.stickyScrollEvent=null;}},onScrollSticky:function(e){var adNode=this.get('boundingBox');if(!adNode.get('region')){return false;}
var y=adNode.getY(),scrollY=window.scrollY||document.documentElement.scrollTop,props=this.stickyAdProps;if(props.isFixedPosition&&scrollY<props.y){this.removeSticky(adNode,props);return;}
if(y<scrollY&&!props.isFixedPosition){props.y=y;this.addSticky(adNode,props);}},_queue:function(fn){googletag.cmd.push(Y.bind(fn,this));},_refresh:function(){googletag.pubads().refresh([this._adSlot]);if(isDebug){console.log('Ad refreshed for ',this._adSlot.getTargeting('slot'))}},_render:function(){var divId=this.get('divId'),slotName=this.get('slotName'),targeting,sizes=this.get('sizes'),width=this.get('width'),height=this.get('height'),responsive=this.get('responsive'),mapping=this.get('mapping'),bps=nfl.layout&&nfl.layout.breakpoints,isResponsive=responsive&&mapping&&Y.Lang.isArray(mapping)&&bps;if(!divId){console.warn('ad requires div id',slotName,width+'x'+height);return;}
if(!sizes||!sizes.length&&width&&height){sizes=[[width,height]];}
if(isResponsive){var sizeMappingBuilder=googletag.sizeMapping(),viewportWidth,bpName,viewportSize,slotSize,mapLen=mapping.length;this._sizeMapping={};Y.Array.each(mapping,function(size,i){bpName=(mapLen<3&&i>0?bps[(bps.length-1)][0]:bps[i][0]);viewportWidth=i==0?0:(mapLen<3&&i>0?bps[(bps.length-1)-1][1]:bps[i-1][1]);viewportSize=[viewportWidth,0];slotSize=size;this._sizeMapping[bpName]=slotSize[0];sizeMappingBuilder.addSize(viewportSize,slotSize);},this);sizes=[mapping.shift()];}
var pubService=googletag.pubads(),adSlot=googletag.defineSlot(slotName,sizes,divId);if(isResponsive){var layout=Y.NFL.getLayout(),sizeMapping=sizeMappingBuilder.build();adSlot.defineSizeMapping(sizeMapping);layout.after('breakpointChange',this._onBreakpointChange,this);this._onBreakpointChange({type:'initial load',newVal:layout.get("breakpoint")});}
if(this.get('interstitial')){this.get('boundingBox').setStyle('height','1px');Y.one(window).on("message",Y.bind(this._onFiFMessage,this));}
adSlot.addService(pubService);this._adSlot=adSlot;targeting=this._setSlotTargeting();pubService.enableAsyncRendering();pubService.addEventListener('slotRenderEnded',Y.bind(this._onSlotRendered,this));googletag.enableServices();googletag.display(divId);if((isMobile||isTablet)&&!outOfPageSlot){Y.one('body').prepend('<div id="'+interstitialId+'"></div>');Y.one('#'+interstitialId).setStyle('position','absolute');outOfPageSlot=Ads.Ad.OUT_OF_PAGE_SLOT=googletag.defineOutOfPageSlot(slotName,interstitialId);outOfPageSlot.addService(pubService).setTargeting('slot','interstitial');googletag.display(interstitialId);}
if(isDebug){console.log('Ad _render',divId,slotName,targeting,sizes);}},_onFiFMessage:function(e){var bbx=this.get('boundingBox'),messageEvent=e._event,data;if(messageEvent.origin.indexOf('nfl.com')>-1){try{data=Y.JSON.parse(messageEvent.data);}catch(err){return;}
if(data&&data.type==='ad'){if(isDebug){console.log('Ad _onFiFMessage',e,messageEvent.origin,data);}
if(data.style){Y.later(10,null,function(){bbx.setStyles(data.style);});}}}},_onBreakpointChange:function(e){var bp=e.newVal,width=this._sizeMapping[bp];if(isDebug){console.log('_onBreakpointChange',bp,this._sizeMapping,width);}
this.get('boundingBox').setStyle('width',width+'px');if(e.type!=='initial load'){this._refresh();}},_setSlotTargeting:function(){var adSlot=this._adSlot,targeting=this.get('targeting');if(!adSlot)return;if(isDebug){console.log('_setSlotTargeting',targeting,adSlot.getTargeting('slot'));}
if(!this._audienceTargeting){this._audienceTargeting=Ads.getAudienceTargeting();}
targeting=Y.merge(targeting,this._audienceTargeting);adSlot.clearTargeting();Y.Object.each(targeting,function(v,k){if(v){adSlot.setTargeting(k,v);}});if(testParam){adSlot.setTargeting('test',testParam);}
return targeting;},_onSlotRendered:function(e){var slot=e.slot,divId=slot.getSlotId().getDomId();if(slot===this._adSlot){if(this.get('interstitial')&&!e.isEmpty&&e.size&&e.size[0]!==1&&e.size[1]!==1){this.get('boundingBox').setStyle('height','auto');}
if(isDebug){if(!e.isEmpty&&e.size){console.log('slotRenderEnded id: '+e.creativeId+' is rendered to slot '+divId+' of size: '+e.size[0]+'x'+e.size[1],e.slot,e);}else{console.log('slotRenderEnded but empty, div id:',divId,e);}}
this.fire(Ads.Ad.AD_RENDERED,e);}},_excludeProps:function(obj){var i=0,len=Ads.Ad.LEGACY_TARGET_EXCLUDES.length;for(;i<len;i++){if(obj.hasOwnProperty(Ads.Ad.LEGACY_TARGET_EXCLUDES[i])){obj[Ads.Ad.LEGACY_TARGET_EXCLUDES[i]]=undefined;}}},_uiRenderCompanion:function(div,html){var doc=Y.config.doc,contentWindow="contentWindow",documentS="document",iframe,page,iframeNode,domainSrc,d;if(!html){return;}
page='<!DOCTYPE html><html><head><meta charset="utf-8"><title></title></head><body style="margin:0;padding:0">'+html+'</body></html>';iframeNode=Y.Node.create("<iframe frameborder=\"0\" allowtransparency=\"true\" scrolling=\"no\" />");iframeNode.setStyles({width:"100%",height:"100%",verticalAlign:"bottom"});div.empty().append(iframeNode);iframe=iframeNode.getDOMNode();try{iframe[contentWindow][documentS].open();}catch(e){domainSrc="javascript:var d="+documentS+".open();d.domain='"+doc.domain+"';";iframe.src=domainSrc+"void(0);";}
try{d=iframe[contentWindow][documentS];d.write(page);d.close();}catch(e2){iframe.src=domainSrc+'d.write("'+html.replace(/"/g,'\\"')+'");d.close();';}},destructor:function(){if(this.stickyScrollEvent){this.stickyScrollEvent.detach();this.stickyScrollEvent=null;}
if(this.checkElementEvent){this.checkElementEvent.detach();this.checkElementEvent=null;}
if(this.stickyViewabilityTimeout){window.clearTimeout(this.stickyViewabilityTimeout);this.stickyViewabilityTimeout=null;}
if(this.slotRenderedViewableTimeout){window.clearTimeout(this.slotRenderedViewableTimeout);this.slotRenderedViewableTimeout=null;}
delete instances[this.get("id")];}},{NAME:'ad',ATTRS:ATTRS,LEGACY_TARGET_EXCLUDES:['nfl','kw','!category','tile','test'],AD_RENDERED:'adRendered'});Ads.create=function(config){return new Ads.Ad(config);};Ads.getAudienceTargeting=function(){var aamnfl=Y.Cookie.exists(COOKIE_AAMNFL)?Y.QueryString.parse(Y.Cookie.get(COOKIE_AAMNFL).replace(/;/g,'&')):{},aamdid=Y.Cookie.exists(COOKIE_AAMDID)?Y.Cookie.get(COOKIE_AAMDID):null;return Y.merge(aamnfl,{u:aamdid});};Ads.resetOrd=function(){console.warn('Ads.resetOrd deprecated, Use GPT tag instead.');};},"3.10.3",{requires:['base-build','widget-base','cookie','json-parse','querystring','gpt','nfl-layout','yui-throttle'],skinnable:true});