YUI.add("geocode",function(Y){"use strict";var PREFIX="geocode:",YLang=Y.Lang,NFLGeoCode=Y.NFLGeoCode=function(){this.initialize.apply(this,arguments);},instance;if(typeof YUI.Env.Geo==='undefined'){YUI.Env.Geo={};}
NFLGeoCode.prototype={check:function(uri){var evtName=PREFIX+uri;if(YLang.isNull(this.getEvent(evtName,true))){this.publish(evtName,{emitFacade:true,broadcast:2,fireOnce:true,async:true});if(this.config.useJSONP){var jsonpUrl=nfl.constants.SITE_URL+"/widget/geocode?uri="+uri+"&callback=YUI.Env.Geo.nflGeoCodeCallback";YUI.Env.Geo.nflGeoCodeCallback=Y.bind(function(_resp){var evtName=PREFIX+uri;this.fire(evtName,{result:_resp});},this);var service=new Y.JSONPRequest(jsonpUrl,YUI.Env.Geo.nflGeoCodeCallback);service.send();}
else{Y.io("/widget/geocode",{data:"uri="+encodeURIComponent(uri),context:this,on:{complete:function(id,xhr){this.fire(evtName,{result:xhr.responseText});}}});}}},initialize:function(config){this.config=config;if(config&&config.uri){this.check(config.uri);}}};Y.augment(NFLGeoCode,Y.EventTarget);Y.getNFLGeoCode=function(uri,callback,useJSONP){var config={useJSONP:useJSONP||false};instance=instance||new NFLGeoCode(config);instance.check(uri);if(YLang.isFunction(callback)){instance.on(PREFIX+uri,function(event){callback(event.result);});}};Y.getNFLGeoCountryCode=function(uri,callback,useJSONP){if(sessionStorage!==null){var _cc=false;try{_cc=sessionStorage['nflgeo_cc'];}catch(e){}
if(_cc){callback(_cc);return}}
Y.getNFLGeoCode(uri,Y.bind(function(_cb,_r){var _cc='US';if(_r){var geo=((typeof _r==='string')?Y.JSON.parse(_r):_r);_cc=(typeof geo.countryCode!=='undefined'&&geo.countryCode!==null)?geo.countryCode:_cc;if(sessionStorage!==null){try{sessionStorage['nflgeo_cc']=_cc;}catch(e){};}}
_cb(_cc);},window,callback),useJSONP);}},"3.3.0",{requires:["io","event-custom","jsonp"]});;YUI.add('nfl-user',function(Y){var COOKIE_USER='userId',COOKIE_SITELIFE='at',COOKIE_PARTNER='ptnr',COOKIE_PARTNER2='partner',COOKIE_FANTASY='ff',SUCCESS_EVENT='fantasydata',FAILURE_EVENT='fantasydatafailure',INPUT="<input type=\"hidden\" />",GIGYA_CID="nfl_global_",GIGYA_CONF=nfl.constants.GIGYA_CONF,SOCIAL_PROVIDER_ADDED_EVENT="socialProviderAdded",SOCIAL_PROVIDER_REMOVED_EVENT="socialProviderRemoved",YLang=Y.Lang,YCookie=Y.Cookie,YArray=Y.Array,YObject=Y.Object,yQueryStringParse=Y.QueryString.parse,yQueryStringStringify=function(obj,c){var qs=[],s=c&&c.arrayKey?true:false,key,i,l;for(key in obj){if(obj.hasOwnProperty(key)){if(Y.Lang.isArray(obj[key])){for(i=0,l=obj[key].length;i<l;i++){qs.push((s?key+'[]':key)+'='+(obj[key][i]));}}
else{qs.push(key+'='+obj[key]);}}}
return qs.join('&');},PLUSES=/\+/g,SPACE=' ',Constants=nfl.constants,User,GlobalEnv=YUI.namespace("Env.NFLUser"),gigya=Y.config.win.gigya;function handleGigyaLoginResponse(response){Y.use("node",function(Y){var cn=Y.Node.create,form=cn('<form action="'+nfl.constants.ID_MANAGER+'/social/login" method="POST" target="_self" style="display:none"><div></div></form>'),user=response.user,inputs;if(response.errorCode+""==="0"){inputs=YArray.map(["UID","UIDSig","UIDSignature","age","birthDay","birthMonth","birthYear","city","email","firstName","gender","lastName","nickname","photoURL","signatureTimestamp","state","thumbnailURL","zip","isSiteUID"],function(field){return cn(INPUT).setAttrs({name:field,value:user[field]});}).concat([cn(INPUT).setAttrs({name:"provider",value:response.requestParams.provider}),cn(INPUT).setAttrs({name:"returnTo",value:window.location.href})]);form.one("div").append(Y.all(inputs));Y.one("body").append(form);form.submit();}});}
function callGigyaMethod(method,config){Y.use("gigya-socialize",function(){Y.config.win.gigya.services.socialize[method](nfl.constants.GIGYA_CONF,config);});}
function loginWithProvider(provider){callGigyaMethod("login",{provider:provider,cid:GIGYA_CID+provider,pendingRegistration:true,callback:handleGigyaLoginResponse});}
User=Y.Base.create('nfl-user',Y.Base,[],{initializer:function(config){if(config){if(config.u){this.set('username',config.u);}
if(config.t){this.set('team',config.t);}
if(config.sps){YArray.each(config.sps.split(","),function(provider){this.set("providers."+provider,true);},this);}
if(config.p){this.set("rememberMe",true);}
if(config.la){this.set("lastAccess",new Date(config.la*1));}}
this.originalConfig=Y.clone(config);this.publish(SUCCESS_EVENT,{emitFacade:true,fireOnce:true,preventable:false});this.publish(FAILURE_EVENT,{emitFacade:true,fireOnce:true,preventable:false});this.publish(SOCIAL_PROVIDER_ADDED_EVENT,{emitFacade:true,broadcast:2,preventable:true,defaultFn:function(event){event.target.setProvider(event.provider,true);}});this.publish(SOCIAL_PROVIDER_REMOVED_EVENT,{emitFacade:true,broadcast:2,preventable:true,defaultFn:function(event){event.target.setProvider(event.provider,false);}});this._fdsRequest={request:'',callback:{success:Y.bind("_onSuccess",this),failure:Y.bind("_onFailure",this)}};},_onSuccess:function(response){this.fire(SUCCESS_EVENT,response.data||response.response.results[0]);},_onFailure:function(response){this.fire(FAILURE_EVENT);},_setUserName:function(value){this.set('profilePageURL','/fans/profile/'+encodeURIComponent(value));},_generateJSONPDataSource:function(){var oldDataSource=this.get('fantasyDataSource'),dataSource=new Y.DataSource.Get({source:Constants.FANTASY_API+this.get('apiURL')});if(oldDataSource){oldDataSource.destroy();}
this.set('fantasyDataSource',dataSource);return dataSource;},_onConnectionAdded:function(response){console.log("[User] _onConnectionAdded(",response,")");if(!response.errorCode){this.fire(SOCIAL_PROVIDER_ADDED_EVENT,{provider:response.requestParams.provider});}},addConnection:function(provider,force){var providers=this.get("providers");if(providers[provider]){return;}
else if(force||YArray.some(YObject.values(providers),function(value){return value;})){callGigyaMethod("addConnection",{provider:provider,cid:GIGYA_CID+provider,callback:Y.bind("_onConnectionAdded",this)});}
else{callGigyaMethod("getUserInfo",{callback:Y.bind(function(response){if(response.user.isSiteUser){this.addConnection(provider,true);}
else{this.registerWithProvider(provider);}},this)});}},_onConnectionRemoved:function(response){console.log("[User] _onConnectionRemoved(",response,")");if(!response.errorCode){this.fire(SOCIAL_PROVIDER_REMOVED_EVENT,{provider:response.requestParams.provider});}},setProvider:function(name,value){var providers=[];this.set("providers."+name,value);YObject.each(this.get("providers"),function(value,key,obj){if(value){providers.push(key);}});User.mergeWithCookie({sps:providers.join(",")});},removeConnection:function(provider){var providers=this.get("providers");if(providers[provider]){callGigyaMethod("removeConnection",{provider:provider,cid:GIGYA_CID+provider,callback:Y.bind("_onConnectionRemoved",this)});}},_onRegisterResponse:function(response){console.log("[User] _onRegisterResponse(",response,")");if(!response.errorCode){this.fire(SOCIAL_PROVIDER_ADDED_EVENT,{provider:response.requestParams.provider});}},registerWithProvider:function(provider){callGigyaMethod("login",{provider:provider,cid:GIGYA_CID+provider,pendingRegistration:true,callback:Y.bind("_onRegisterResponse",this)});},getFantasyData:function(force,cb){var fds=this.get('fantasyDataSource');if((!fds)||force){fds=this._generateJSONPDataSource();}
if("function"===typeof cb){fds.once("*:response",cb);}
fds.sendRequest(this._fdsRequest);},destructor:function(){var dataSource=this.get('dataSource');if(dataSource){dataSource.destroy();}}},{SOCIAL_PROVIDER_ADDED_EVENT:SOCIAL_PROVIDER_ADDED_EVENT,SOCIAL_PROVIDER_REMOVED_EVENT:SOCIAL_PROVIDER_REMOVED_EVENT,loginWithProvider:loginWithProvider,ATTRS:{apiURL:{value:"/internal/user/leagues?format=json&"},fantasyDataSource:{value:null},lastAccess:{valueFn:function(){return new Date();}},profilePageURL:{value:null},providers:{valueFn:function(){return YArray.reduce(Constants.GIGYA_CONF.enabledProviders.split(","),{},function(init,provider){init[provider]=false;return init;});}},rememberMe:{value:false,validator:YLang.isBoolean},team:{value:' '},username:{value:null,setter:'_setUserName'}},parseFantasyCookie:function(){var data=arguments[0]||YCookie.get(COOKIE_FANTASY,yQueryStringParse);return Y.NFL.Fantasy.ServiceUtility.PARSE_FANTASY_COOKIE_DATA(data);},getCurrent:function(){if(GlobalEnv.user){return GlobalEnv.user;}
var nflCookie=YCookie.get(COOKIE_USER,yQueryStringParse),pluckCookie=YCookie.get(COOKIE_SITELIFE,yQueryStringParse),partnerCookie=YCookie.get(COOKIE_PARTNER,yQueryStringParse),fantasyCookie=YCookie.get(COOKIE_FANTASY,yQueryStringParse),username=nflCookie?nflCookie.u:'',u;if(username&&nflCookie&&pluckCookie&&partnerCookie&&username===pluckCookie.u&&username===partnerCookie.u){u=new User(nflCookie);if(fantasyCookie&&fantasyCookie!=='0'){u.set('fantasyDataSource',new Y.DataSource.Local({source:User.parseFantasyCookie(fantasyCookie)}));}
u.after("providersChange",function(event){var providers=[];YObject.each(event.newVal,function(value,key){if(value){providers.push(key);}});User.mergeWithCookie({sps:providers.join(",")});});GlobalEnv.user=u.plug(Y.UserMetaData);return u;}else if(nflCookie||pluckCookie||partnerCookie){if((nflCookie&&Y.Lang.isUndefined(nflCookie.removed))||(pluckCookie&&Y.Lang.isUndefined(pluckCookie.removed))||(partnerCookie&&Y.Lang.isUndefined(partnerCookie.removed))){if(nflCookie){Y.Cookie.remove(COOKIE_USER);}
if(pluckCookie){Y.Cookie.remove(COOKIE_SITELIFE);}
if(partnerCookie){Y.Cookie.remove(COOKIE_PARTNER);}}}
return false;},mergeWithCookie:function(obj){var cookie=Y.merge(YCookie.get(COOKIE_USER,yQueryStringParse),obj),config={path:"/",domain:".nfl.com"},expiry;if(cookie.p==="true"){expiry=new Date(cookie.d*1);expiry.setUTCFullYear(expiry.getUTCFullYear()+1);config.expires=expiry;}
YCookie.set(COOKIE_USER,yQueryStringStringify(cookie),config);},getAvatar:function(cb){var NO_USER_IMAGE='http://i.nflcdn.com/static/site/img/community/profile/no-avatar.png',callback=cb||function(avatar){return avatar};callback(NO_USER_IMAGE);},FANTASY_DATA:SUCCESS_EVENT,FANTASY_FAILURE:FAILURE_EVENT});User.getCurrent();Y.NFLUser=Y.namespace("NFL").User=User;},"3.3.0",{requires:['array-extras','user-meta','base-build','cookie','querystring','datasource-local','datasource-get',"plugin",'nfl-lang','jsonp-url','nfl-user-fantasy']});;YUI.add('nfl-subscriptions',function(Y){Y.namespace('NFL').Subscriptions=Y.Base.create("nfl-subscriptions",Y.Base,[],{initializer:function(config){this.publish('responded',{emitFacade:true,fireOnce:true,preventable:false});if(config.user){this.set('user',config.user);}else{this.set('user',Y.NFL.User.getCurrent());}
if(config.onResponse){this.on('responded',config.onResponse);}
Y.Global.onceAfter('subscriptionResponded',function(e){if(!this.get('ready')){this.set('subscriptions',e.subscriptions);this.set('ready',true);}
this.fire('responded',{subscriptions:this.get('subscriptions')});},this);if(!YUI.namespace('Env.Subscription').instance){YUI.namespace('Env.Subscription').instance=this;Y.Global.publish('subscriptionResponded',{fireOnce:true});this.after('readyChange',this._afterResponded,this);if(this.get('user')===null||this.get('user')===false){this.set('ready',true);return;}
if(this._hasCookie()&&this.setSubsFromCookie()){this.set('ready',true);return;}
this.setSubsFromService();}},_getCookie:function(){var _val=Y.Cookie.get("nflsubs");return((typeof _val==='undefined'||_val===null)?null:_val.replace(/^"|"$/g,''));},_hasCookie:function(){return(this.get('cookie')!==null);},_afterResponded:function(_c){Y.Global.fire('subscriptionResponded',{subscriptions:this.get('subscriptions')});},_onDataResponse:function(r){console.info('subscription service response',r);if(r.response===null){this.set('ready',true);return;}
if(r.response.results===null){this.set('ready',true);return;}
if(r.response.results.length===0){this.set('ready',true);return;}
var _subs=[];Y.Array.each(r.response.results,function(_s){if(_s.active!==false&&Y.Array.indexOf(_subs,_s.type)<-0){_subs.push(_s.type);}},this);this.set('subscriptions',_subs);this.set('ready',true);},_onDataFailure:function(){this.set('ready',true);},hasSubscription:function(_subkey){if(this.get('subscriptions')!==null){if(this.get('subscriptions').length>0){if(Y.Array.indexOf(this.get('subscriptions'),_subkey)>-1){return true;}}}
return false;},setSubsFromCookie:function(){var _c,_vals,_subs;_c=this.get('cookie');if(_c===null){return;}
_vals=_c.split('|');_subs=[];if(this.get('user').get('username')===_vals[0]){try{var _val=Y.Lang.trim(_vals[1]);if(_val===''){return false;}
this.set('subscriptions',((_val.indexOf(',')>-1)?_val.split(","):[_val]));return true;}catch(_e){console.error(_e);}}
return false;},setSubsFromService:function(){this.set('ready',true);return false;this.set('ds',new Y.DataSource.Get({source:"http://subscriptions.nfl.com/nflsubs/subcheck?"}));this.get('ds').sendRequest({callback:{success:Y.bind(this._onDataResponse,this),failure:Y.bind(this._onDataFailure,this)}});},destroy:function(){try{if(this.get('ds')!==null){this.get('ds').destroy();}
if(this.get('user')!==null){this.get('user').destroy();}}catch(e){}}},{'NAME':"Subscriptions",'ATTRS':{'ds':{value:null},'user':{value:null},'ready':{value:false},'subscriptions':{value:[]},'cookie':{getter:'_getCookie'}}});},"3.1.1",{requires:['array-extras','base-build','cookie','datasource-get','event','event-custom','nfl-lang','nfl-user']});